name = "Migrate"
main = "Migrate"
authors = ["Jakob Lautrup Nysom", "Patrick Evers Bjørkman", "Stinus Møhl Thomsen"]
libraries = [
    "Newtonsoft.Json",
    "Pastry",
]

includes = [
    "binaries"
]

[targets] # Dependencies
# Send = ["Repository_types"]
Repository_types = ["Pastry"]
Migrate = ["Repository_types"]
# EventLogic = ["Repository_types"]
# UserLogic = ["Repository_types"]
# WorkflowLogic = ["Repository_types"]
# RestAPI = ["Repository_types", "EventLogic", "WorkflowLogic", "UserLogic", "Pastry"]