name = "Program"
main = "Program"
authors = [
    "Jakob Lautrup Nysom", "Patrick Evers Bjørkman",
    "Stinus Møhl Thomsen", "Aslak Vanggaard"]
libraries = [
    "Newtonsoft.Json",
    "Pastry",
    "PastryTypes",
    "PastryUtils",
    "WebClientWithTimeout",
]

includes = [
    "binaries"
]

[targets] # Dependencies
Send = ["Repository_types", "Pastry"]
Repository_types = ["Pastry"]
Migrate = ["Repository_types"]
EventLogic = ["Repository_types", "Pastry", "Send"]
UserLogic = ["Repository_types", "EventLogic", "Pastry"]
WorkflowLogic = ["Repository_types", "Pastry", "EventLogic"]
RestAPI = [
    "Repository_types", "EventLogic", "WorkflowLogic",
    "UserLogic", "Pastry", "Migrate", "Newtonsoft.Json"
]
Program = ["RestAPI", "Pastry", "Newtonsoft.Json"]