name = "PastryDemo"
main = "PastryDemo"
authors = ["Jakob Lautrup Nysom"]
libraries = [
    "Newtonsoft.Json"
]

includes = [
    "binaries"
]

[targets] # Dependencies
Pastry = ["PastryTypes", "PastryUtils"]
PastryTypes = []
PastryUtils = ["PastryTypes", "Newtonsoft.Json"]
PastryDemo = ["Pastry"]
