name = "Pastry"
main = "pastry_demo"
authors = ["Jakob Lautrup Nysom"]
libraries = [
    "Newtonsoft.Json"
]

includes = [
    "binaries"
]

[targets] # Dependencies
pastry = ["pastry_types", "pastry_utils"]
pastry_types = []
pastry_utils = ["pastry_types", "Newtonsoft.Json"]
pastry_demo = ["pastry"]
